name: Python Package using Conda

on: [push,workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11
        
    - name: PowerShell
      shell: powershell
      run: |
        conda info
        conda list

