name: pip-ci

on: [workflow_dispatch, push]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\my-env

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: my-env
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('requirements.txt') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment requirements
        run: mamba env update -n my-env -f .\requirements.txt -c conda-forge
        if: steps.cache.outputs.cache-hit != 'true'
        
      - name: Activate environment  
        run: conda activate my-env
        if: steps.cache.outputs.cache-hit != 'true'
        
      - name: Update environment setuptools
        run: pip install opencv-python
        if: steps.cache.outputs.cache-hit != 'true'
        
      - name: Update environment setuptools
        run: pip install setuptools==59.5.0
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Update environment torch
        run: pip install torchvision==0.11.3 -f https://download.pytorch.org/whl/cu111/torch_stable.html
        if: steps.cache.outputs.cache-hit != 'true'
