name: pip-ci

on: [workflow_dispatch, push]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    name: win-64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: my-env
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: c:\hostedtoolcache\windows\python\3.9.13\x64\lib\site-packages
          key: win-64-conda-${{ hashFiles('requirements.txt') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: |
          pip install -r .\requirements.txt 
          pip install setuptools==59.5.0
          pip install torchvision==0.11.3 -f https://download.pytorch.org/whl/cu111/torch_stable.html
          pip install pytest
        if: steps.cache.outputs.cache-hit != 'true'
      
      - name: Run tests
        run: |
          pytest test_detect_image.py
